# Use an official Node.js runtime as a parent image
FROM node:16-alpine AS build

# Set the working directory in the container
WORKDIR /dist/src/app

RUN npm cache clean --force
# Copy package.json and package-lock.json files
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build:dev

# Stage 2: Serve the app with nginx server
FROM nginx:latest AS ngi
COPY --from=build /dist/src/app/dist/free-notes-client /usr/share/nginx/html
COPY /nginx.conf  /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]
